Add remove functions implementation
Hombre2014/Book-store pull request #2
Opened 2022-01-25 20:40 UTC by Hombre2014

### Phase 2, create and remove books
- [x] Configuring the Redux Store
- [x] Write book's actions and reducer
- [x] In the React component responsible for adding new books set the data inputs in the local React state (set title and author - NOTE: categories and comments are NOT part of this step). Once your new book object is ready to be submitted to Redux store, dispatch a corresponding action.
- [x] In the React component responsible for removing books - implement that event by dispatching a corresponding action.
- [x] Use the redux-logger to check if your application is working correctly - Open your browser's console and look for the logger messages. Upon every action dispatch, the logger will print:
  - [x] prev state - the state of the whole Redux store before the current action was dispatched.
  - [x] action - the action object that is being dispatched.
  - [x] next state - the state of the Redux store after the current action was dispatched.

2022-01-25 20:58 UTC, ZeenatLawal requested changes
Hi @Hombre2014, 

Good job so far!:clap: :clap:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎊 🎊 
- Git flow is followed. ✔️
- PR has a title and summary. ✔️


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-25 20:58 UTC, ZeenatLawal commented on src/redux/configureStore.js
> +// import { initialState } from './books/books';
- [ ] Kindly remove commented out codes to follow best practices.

2022-01-25 20:58 UTC, ZeenatLawal commented on src/redux/configureStore.js
> +  // (state, action) => reducer(state, action), initialState,
- [ ] Kindly remove commented out codes to follow best practices.

2022-01-25 20:58 UTC, ZeenatLawal commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'REMOVE_BOOK';
- [ ] Action types should be written using ducks pattern as stated in the requirements. The action types should be written in a format like this `const ADD_BOOK = 'appname/reducer/ACTION_TYPE';`. Kindly modify this.

2022-01-25 20:58 UTC, ZeenatLawal commented on src/redux/books/books.js
> +      return [...state.filter((book) => book.id !== action.payload)];
- [ ] The REMOVE_BOOK action type should a new array as stated in the requirements. I would suggest applying the filter directly without spreading it in another array, you could write it like this `return state.filter(book => book.id !== id);`

2022-01-26 07:53 UTC, Hombre2014 commented
Thanks for your comment and recommendations. All the required changes have been implemented.

2022-01-26 08:03 UTC, dasileker approved these changes
## **Hi @Hombre2014 ,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-26 08:42 UTC, merged